### ISSUE TITLE
Upload package to PyPI, to make it installable with pip

### ISSUE THREAD

**Issue by fisadev** [Holiverh/python-valve#15]
I can help if you need anything!

**Comment by Holiverh** [comment]
Yup. I've been reluctant to add it to Pypi because it's still kinda broken in places, lacks test coverage and other minor things, but whatevs.

It should've been directly installable from the repo with pip already but that seems to be broken. I'll set some time aside to fix it.

**Comment by PhilipCammarata** [comment]
Using the pip install method via Python 3.4.0 on Ubuntu 14.04 I get a success install:

```
$ pip install git+https://github.com/Holiverh/python-valve.git
Downloading/unpacking git+https://github.com/Holiverh/python-valve.git
  Cloning https://github.com/Holiverh/python-valve.git to /tmp/pip-_b9n_7t0-build
  Running setup.py (path:/tmp/pip-_b9n_7t0-build/setup.py) egg_info for package from git+https://github.com/Holiverh/python-valve.git

Requirement already satisfied (use --upgrade to upgrade): six>=1.6 in ./.virtualenvs/pytf2/lib/python3.4/site-packages/six-1.9.0-py3.4.egg (from python-valve==0.0)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0 in ./.virtualenvs/pytf2/lib/python3.4/site-packages/requests-2.5.1-py3.4.egg (from python-valve==0.0)
Installing collected packages: python-valve
  Running setup.py install for python-valve

Successfully installed python-valve
Cleaning up...
```

Cool.  The issue I run into is when I then try to use python-valve.

```
Python 3.4.0 (default, Apr 11 2014, 13:05:11)
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import valve
>>> import valve.steam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'valve.steam'
```

    import valve # this works

    import valve.steam # this raises the ImportError
    import valve.source # same thing

**Comment by PhilipCammarata** [comment]
The below pull request solves the installation issue.

https://github.com/Holiverh/python-valve/pull/16

**Comment by TimotheeJeannin** [comment]
It would be great to have this on Pypi ! Thank you for this awesome project. :)

**Comment by Holiverh** [comment]
https://pypi.python.org/pypi/python-valve
