### ISSUE TITLE
Is there any way to read the console/server chat?

### ISSUE THREAD

**Issue by flubbateios** [Holiverh/python-valve#24]
For instance, if I say 'hi' in the game chat, the console will display ' flubb:hi ' , or something similar. Is there a way to read this data from the server's console?

**Comment by Holiverh** [comment]
AFAIK, no. RCON is a simple request-reply protocol. Unless there is a command which returns the chat log (which I'm pretty certain there isn't) RCON isn't the tool you're looking for in this case.

**Comment by flubbateios** [comment]
so I would have to do something server side?

**Comment by Holiverh** [comment]
I believe so, yes. But, you could also check through what commands are available; there may be one that's of use to you.
