### ISSUE TITLE
Add support for EDF

### ISSUE THREAD

**Issue by Coriou** [Holiverh/python-valve#31]
I'm trying to use this for Rust and I think the field I'm after ("gametags") is an extra data field.

**Comment by Coriou** [comment]
Reproducible code:

[https://gist.github.com/Coriou/216462bd12fe3454f0fd](Gist)

Will return:

> map Procedural Map
player_count 59
protocol 17
server_name London - Staging
server_type Non-Dedicated
max_players 200
password_protected 0
app_id 0
platform Windows
game rust_server
version 1355
response_type 73
vac_enabled 1
folder rust
bot_count 0

**Comment by Coriou** [comment]
Bump ?

**Comment by Mambix** [comment]
@Coriou how do you connect to Rust server?
I'm having issues connecting to mine described here: https://github.com/Holiverh/python-valve/issues/38
