### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by LiberBear** [Holiverh/python-valve#35]
Can someone tell me how can i use this lib with proxy?

**Comment by WhiteyDude** [comment]
Just like any other python script with a proxy I would presume, set environment variables like http_proxy and https_proxy

**Comment by Holiverh** [comment]
I assume this is referring `valve.steam.api`? If so, @WhiteyDude nailed it. Python-valve uses `requests` for all it's HTTP interactions. Requests respects `HTTP_PROXY` and `HTTPS_PROXY` environment variables: http://docs.python-requests.org/en/latest/user/advanced/#proxies

If you feel python-valve could expose this behaviour better feel free to reopen this issue. I'll probably add a notice to the docs regardless. So 👍 for the report.
