### ISSUE TITLE
under linux low unique servers, mostly duplicates

### ISSUE THREAD

**Issue by Megido6** [Holiverh/python-valve#39]
```
import valve.source.a2s
import valve.source.master_server
s=set()
msq = valve.source.master_server.MasterServerQuerier()
try:
    for address in msq.find(
            gamedir=u"7dtd"):
        s.add(address)
        print len(s)
except valve.source.a2s.NoResponseError:
    print "Master server request timed out!"

```

~4600 unique  on windows
~ 670 unique  on linux

**Comment by Holiverh** [comment]
`MasterServerQuerier` simply returns the server address as it gets them from the master server. Any duplication or a low number of unique servers is a product of what the master server is returning to python-valve.

The master servers are notoriously flaky. Sometimes returning thousands of unique addresses. Sometimes returning nothing. There's not a great deal that can be done about it sadly. I have noticed that making loads of master server requests in close succession certainly doesn't seem to help.

Specifically in regards to duplicate entries: you might want to have a gander at #34.
