### ISSUE TITLE
TypeError on ServerQuerier.info()

### ISSUE THREAD

**Issue by jonlee836** [Holiverh/python-valve#44]
```
import valve.source.a2s
import valve.source.master_server

#from valve.source import a2s
#from valve.source import master_server

server = valve.source.a2s.ServerQuerier('162.248.88.218' , 7777)
info = server.info()
```
Which results in the following error.

     1	Traceback (most recent call last):
     2	  File "query.py", line 8, in <module>
     3	    info = server.info()
     4	  File "/usr/lib/python3.6/site-packages/python_valve-1.0.0-py3.6.egg/valve/source/a2s.py", line 160, in info
     5	  File "/usr/lib/python3.6/site-packages/python_valve-1.0.0-py3.6.egg/valve/source/a2s.py", line 51, in request
     6	TypeError: an integer is required (got type str)

Help would be appreciated.

**Comment by Yepoleb** [comment]
Put another pair of brackets around the address pair to make it a tuple:

    server = valve.source.a2s.ServerQuerier(('162.248.88.218', 7777))
