### ISSUE TITLE
Python2.7

### ISSUE THREAD

**Issue by AncientEntity** [Holiverh/python-valve#45]
So im pretty sure I read that it works for 2.7 if im wrong im sorry for being a failiure anyways when i run the setup it breaks It prints some stuff closes then when I try to import it in another python file it doesnt work.

**Comment by Holiverh** [comment]
Python 2.7 is indeed supported. Can you provide more details about the manner in which it breaks for you? Any stack traces and error messages would be a start. A reproducible example ideally. 👍

**Comment by Holiverh** [comment]
Please try the new 0.2.0 release. If it's still broken for you feel free to reopen this issue.
