### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by Yepoleb** [Holiverh/python-valve#46]
The last version there is from 2015-11-25.

**Comment by digitalfiz** [comment]
Yes please! I was wondering why it kept erroring on trying to use info() and its because the pypi version is old and its get_info().

**Comment by Holiverh** [comment]
[Python-valve 0.2.0](https://pypi.python.org/pypi/python-valve/0.2.0) has been uploaded to PyPI! Please take note of the README section about versioning going forwards.
